src/ERP/UserBundle/Entity/User.php
<?php

namespace ERP\UserBundle\Entity;

use CoreBundle\Traits\CreatedAtableEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="erp_user")
 * @ORM\Entity(repositoryClass="ERP\UserBundle\Repository\UserRepository")
 */
class User
{
    use CreatedAtableEntity;

    /** @ORM\ManyToOne(targetEntity="UserBundle\Entity\User") */
    private $user;

    /** @ORM\OneToMany(targetEntity="ERP\DocumentBundle\Entity\Document", mappedBy="user", cascade={"persist"}) */
    private $documents;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $society;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tvaNumber;

    public function getCodeWithCompleteName()
    {
        $code = $this->getCode();

        return $code.' - '.$this->getCompleteName();
    }

    public function getCompleteName()
    {
        $society = $this->getSociety();
        $name = $this->getLastName().', '.$this->getFirstName();
        if ($name == ', ') $name = '';
        if ($society != '' && $name != "") $society = $society.' - ';

        return $society.$name;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set society
     *
     * @param string $society
     *
     * @return User
     */
    public function setSociety($society)
    {
        $this->society = $society;

        return $this;
    }

    /**
     * Get society
     *
     * @return string
     */
    public function getSociety()
    {
        return $this->society;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set user
     *
     * @param \UserBundle\Entity\User $user
     *
     * @return User
     */
    public function setUser(\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set code
     *
     * @param string $code
     *
     * @return User
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set tvaNumber
     *
     * @param string $tvaNumber
     *
     * @return User
     */
    public function setTvaNumber($tvaNumber)
    {
        $this->tvaNumber = $tvaNumber;

        return $this;
    }

    /**
     * Get tvaNumber
     *
     * @return string
     */
    public function getTvaNumber()
    {
        return $this->tvaNumber;
    }

    /**
     * Set documents
     *
     * @param \ERP\DocumentBundle\Entity\Document $documents
     *
     * @return User
     */
    public function setDocuments(\ERP\DocumentBundle\Entity\Document $documents = null)
    {
        $this->documents = $documents;

        return $this;
    }

    /**
     * Get documents
     *
     * @return \ERP\DocumentBundle\Entity\Document
     */
    public function getDocuments()
    {
        return $this->documents;
    }
}

src/ERP/UserBundle/Form/UserType.php
<?php

namespace ERP\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code', null, [
                "label" => "Code TIERS"
            ])
            ->add('society', null, [
                "label" => "Société"
            ])
            ->add('lastName', null, [
                "label" => "NOM"
            ])
            ->add('firstName', null, [
                "label" => "Prénom"
            ])
            ->add('tvaNumber', null, [
                "label" => "N° TVA"
            ])
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ERP\UserBundle\Entity\User'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'erp_userbundle_user';
    }


}

src/ERP/UserBundle/Controller/ParentController.php
<?php

namespace ERP\UserBundle\Controller;

class ParentController extends \CoreBundle\Controller\ParentController
{

}

src/ERP/UserBundle/Controller/UserController.php
<?php

namespace ERP\UserBundle\Controller;

use ERP\DocumentBundle\Entity\Sheet;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;

class UserController extends ParentController
{
    /**
     * @Route(
     *     "admin/erp/user/user/table",
     *     name="admin_erp_user_user_table"
     * )
     */
    public function tableAction($parameters = null)
    {
        $parameters['repository_method'] = "findByUser";
        $parameters['repository_argument'] = $this->getUser();
        return parent::tableAction($parameters);
    }

    /**
     * @Route(
     *     "admin/erp/user/user/add",
     *     name="admin_erp_user_user_add"
     * )
     */
    public function addAction(Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_user_user_add');

        return parent::addAction($request, $parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @Route(
     *     "admin/erp/user/user/update/{id}",
     *     name="admin_erp_user_user_update",
     *     requirements={"id" = "\d+"}
     * )
     */
    public function updateAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_user_user_update', [
            "id" => $id
        ]);

        return parent::updateAction($id, $request, $parameters);
    }

    /**
     * @Route(
     *     "admin/erp/user/user/delete/{id}",
     *     name="admin_erp_user_user_delete",
     *     requirements={"id" = "\d+"},
     *     options = {"expose" = true}
     * )
     */
    public function deleteAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = $this->generateUrl('admin_erp_user_user_delete');

        return parent::deleteAction($id, $request, $parameters);
    }
}

src/ERP/UserBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace ERP\UserBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/');

        $this->assertContains('Hello World', $client->getResponse()->getContent());
    }
}

src/ERP/UserBundle/Resources/views/User/add.html.twig
{% include '@ERPUser/User/form.html.twig' %}

src/ERP/UserBundle/Resources/views/User/edit.html.twig
{% include '@ERPUser/User/form.html.twig' %}

src/ERP/UserBundle/Resources/views/User/form.html.twig
{{ form_start(form) }}
<div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title"><i class="fa fa-folder"></i> Nouveau journal</h4>
</div>
<div class="modal-body">
    {{ form_rest(form) }}
</div>

{% include 'CoreBundle:Button:ModalButtons.html.twig' %}

{{ form_end(form) }}

src/ERP/UserBundle/Resources/views/User/table.html.twig
{% extends "@ERPDocument/admin.html.twig" %}

{% block metaTitle %}
    Documents
{% endblock %}

{% block title %}
    Clients
{% endblock %}

{% block titleSmall %}
    Vos clients
{% endblock %}

{% block titleAction %}
    <a href="{{ path('admin_erp_user_user_add') }}"
       class="btn btn-primary"
       data-toggle="modal"
       data-dismiss="modal"
       data-target="#modal">
        <i class="fa fa-plus-circle"></i> Nouveau
    </a>
{% endblock %}

{% block body %}

    <div class="col-md-12 no-padding">
        <div class="box box-primary">
            <div class="box-body">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Code</th>
                        <th>Nom</th>
                        <th>N° TVA</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>
                                <a href="{{ path('admin_erp_user_user_update', {id: user.id}) }}" data-toggle="modal" data-dismiss="modal" data-target="#modal">{{ user.code }}</a>
                            </td>
                            <td>{{ user.completeName }}</td>
                            <td>{{ user.tvaNumber }}</td>
                            <td>
                                <div class="btn-group btn-group-xs">
                                    <a href="{{ path('admin_erp_user_user_update', {id: user.id}) }}" class="btn btn-default" data-toggle="modal" data-dismiss="modal" data-target="#modal"><i class="fa fa-pencil"></i></a>
                                    <a href="{{ path('admin_erp_user_user_delete', {id: user.id}) }}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}